# Generated by Django 2.2.2 on 2019-06-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cpf', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('historico', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteJoga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempoDeJogo', models.PositiveIntegerField()),
                ('cpf', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.Jogos')),
            ],
            options={
                'unique_together': {('nome', 'cpf')},
            },
        ),
    ]
