# Generated by Django 2.2.1 on 2019-07-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cpf', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('historico', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteJoga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempoJogo', models.PositiveIntegerField()),
                ('quantidadeAcertos', models.PositiveIntegerField()),
                ('quantidadeErros', models.PositiveIntegerField()),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('cpf', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
                ('nomeJogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.Jogos')),
            ],
        ),
    ]
