# Generated by Django 2.2.2 on 2019-06-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteJoga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('tempoDeJogoTotal', models.PositiveIntegerField()),
                ('idJogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.Jogos')),
            ],
        ),
    ]
