# Generated by Django 2.1.2 on 2018-10-18 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('cpf', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('contato', models.CharField(max_length=45)),
                ('especialidade', models.CharField(max_length=45)),
                ('cnpj_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Trabalha_Em',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=45)),
                ('cnpj_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Clinica')),
                ('cpf_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissional.Profissional')),
            ],
        ),
    ]
